### ISSUE TITLE
Testing: Should each language test download its own documents?

### ISSUE THREAD

**Issue by plocket** [GBLS/docassemble-MAEvictionDefense#156]
That is, if the test goes through a scenario in Spanish, should it download a zip file at the end that is _separate_ from the one that was downloaded for the same scenario in English? Or is one zip file per scenario sufficient?

Also, do we think that other da projects out in the world would need these to be separate? Could they have logic in their translated blocks that would affect the creation of their documents? It's at least possible technically I suppose.

**Comment by plocket** [comment]
What was the answer to this?

**Comment by nonprofittechy** [comment]
The docs are supposed to be the same

**Comment by plocket** [comment]
Would the docs eventually need to be tested separately?

**Comment by plocket** [comment]
On second thought, maybe those options could have some user testing. In practice, maybe those would be good. It would require extra steps from the developer (finding the name of the test and checking the test itself) and I don't think I can guess at the pain point there. Maybe it wouldn't be a pain at all.

**Comment by nonprofittechy** [comment]
For some theoretical future, sure.

I actually don't think these documents are identical even though they are
supposed to be, because they pick up the date formatting from the user's
language.

I guess a test could catch that error, although it was not a high priority
for me. In some cases, you might have an intentionally different language
in the output document. E.g., cover page with instructions.

If you are thinking of adding a feature it could have a theoretical use. It
wouldn't be my highest priority one, so that's really you to your
discretion.
