### ISSUE TITLE
Add courtformsonline.org metadata

### ISSUE THREAD

**Issue by nonprofittechy** [GBLS/docassemble-MAEvictionDefense#268]

**Comment by samglover** [comment]
@nava-ebad: Since you don't have access to this organization I can't assign this issue to you and you will have to fork this repository before you can commit changes to a branch.

All you have to do is go to [the repository page](https://github.com/GBLS/docassemble-MAEvictionDefense) and click the **Fork** button (it's between **Watch** and **Star**).

Once you have done that you can pull the forked repo to a playground project (the URL will have your GitHub username in it, like `https://github.com/nava-ebad/docassemble-MAEvictionDefense`).

When you are done you can do a pull request from your forked repo to the primary repo, just as if you were doing a pull request from a branch to main. I can walk you through any of these steps if you get stuck.
